version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=web/views.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - ./:/app
    command: flask run --host=0.0.0.0
